-- AlterTable
ALTER TABLE "Campaign" ALTER COLUMN "image" DROP NOT NULL,
ALTER COLUMN "goal" SET DATA TYPE BIGINT,
ALTER COLUMN "collected" SET DEFAULT 0,
ALTER COLUMN "collected" SET DATA TYPE BIGINT;
